name: Deploy

on: [push]
branch: [master]

jobs:
  build-image:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build image
        run: docker build -t wdinx/apriori-golang:latest .
      - name: login registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push image
        run: docker push wdinx/apriori-golang:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: deploy-to-droplets
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPRHASE }}
          script: |
            cd ~/
            docker pull wdinx/apriori-golang:latest
            docker container rm -f apriori
            docker run -d --name apriori -p 3007:3007 --env DBHOST=${{ secrets.DBHOST }} --env DBPORT=${{ secrets.DBPORT }} --env DBUSER=${{ secrets.DBUSER }} --env DBPASS=${{ secrets.DBPASS }} --env DBNAME=${{ secrets.DBNAME }} --env DO_ACCESS_TOKEN=${{ secrets.DO_ACCESS_TOKEN }} --env DO_SECRET_KEY=${{ secrets.DO_SECRET_KEY }} --env DO_REGION=${{ secrets.DO_REGION }} --env DO_BUCKET=${{ secrets.DO_BUCKET }} --env DO_ENDPOINT=${{ secrets.DO_ENDPOINT }} wdinx/apriori-golang:latest
